import type { Metadata } from 'next'

import './globals.css'

import { fontSans } from '@/fonts'

import { cn } from '@/lib/utils'

import { Providers } from '@/components/layouts/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn('bg-background font-sans antialiased', fontSans.variable)}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
